### ISSUE TITLE
Google Cloud- Unable SSH into instance via cloud shell.

### ISSUE THREAD

**Issue by spacetimeengineer3** [chadgeary/cloudblock#21]
Unable to ssh into instance via Google Cloud. This may be because the ssh-keys metadata is throwing out wacky errors in gcp-instance.tf file.

**Comment by spacetimeengineer3** [comment]
> Unable to ssh into instance via Google Cloud. This may be because the ssh-keys metadata is throwing out wacky errors in gcp-instance.tf file.

commenting out a line to see if that fixes it

**Comment by spacetimeengineer3** [comment]
That didn't work. Did find this new error though 

Invalid key. Required format: <protocol> <key-blob> <username@example.com> or <protocol> <key-blob> google-ssh {"userName":"<username@example.com>","expireOn":"<date>"}

**Comment by spacetimeengineer3** [comment]
Alright, it looks like when you press the "add ssh key" button on the VM instance, google attempts to add keys BUT this kills the unbuntu user and then you lose access to your instance. Looking into how to use OS login instead.

**Comment by chadgeary** [comment]
I know we chatted about this on discord - but do you have the error you mentioned in the first comment? Was it from terraform or in the gcp web console?

**Comment by spacetimeengineer3** [comment]
It is caused by something that terraform is configuring. Because of the first issue, the second issue is happening.

**Comment by spacetimeengineer3** [comment]
I am still running it down in my free time because otherwise the script works great!

**Comment by chadgeary** [comment]
To recap, the malformed SSH key is fixed in 001c50c

google cloud ssh keys work with or without a key name. e.g.: `ssh-rsa some_key_data my_key_name` or `ssh-rsa some_key_data`) BUT if the key name is omitted the google cloud web console complains.

I've added logic in terraform to add `ubuntu` as the key name if the user does not supply a key name in `gcp.tfvars`, which should clear that error up.

To re-iterate - a missing key name would not have prevented SSH access. Going to close this as solved.
