### ISSUE TITLE
dinamic ip

### ISSUE THREAD

**Issue by robertogaxiola** [chadgeary/cloudblock#4]
Hi, my isp does not provide me with a static public ip address, its dynamic, what do i put on the  mngt_cidr variable?? if i use my current ip it will work until my ip changes...

**Comment by chadgeary** [comment]
You have a few options

1. Update firewall rules if your IP changes
* Update mgmt_cidr with your new IP
* re-apply the terraform state

2. Stick to wireguard clients instead of direct DNS queries to the pihole
* Wireguard clients use a VPN connection to talk with the Pihole, the firewall isn't a factor
